version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - echo Buildspec setup complete
  build:
    commands:
      - echo Build started on `date`
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform apply -input=false -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
